doha/app.js

Feat: 안녕을 출력하는 함수 기능 추가

---

src/Components/common/TopNavBar.jsx

- mobile first를 위해 min-width로 변경했습니다.
- 이미지 경로가 잘못되어 경로 수정되었습니다.
open : #12 
close :

Design: 이미지 import 경로 변경, 레이아웃 width를 min-width로 변경 (#12)

---

src/Components/common/TopNavBar.jsx
src/Components/common/User.jsx
src/Pages/Home.jsx

- User 컴포넌트 if문 대신 &&연산자로 변경했습니다!
open : #16
close : #

Refactor: User 컴포넌트 리팩토링 (#16)

---

src/Components/common/Input.jsx

- input에 margin-bottom 10px 고정값으로 추가했습니다.
open : #12 
close : #

Design: 공통 컴포넌트 label margin-bottom 추가 (#12)

---

src/Components/common/Input.jsx

- commit에 이슈 번호 28이라 작성돼있지만 24번 입니다.....
open : #
close : #24

Fix: Input 포커스시 margin bottom 수정(#28)

---

src/Components/common/User.jsx

- User 컴포넌트 props 부분 수정하였습니다.
open : #
close : #

Refactor: User 컴포넌트 props 부분 수정 (#16)

---

src/Components/common/User.jsx

- username의 padding-bottom을 margin-bottom 2px로 변경
open : #12 
close : #

Design: username의 padding-bottom을 margin-bottom 2px로 변경 (#12)

---

src/Components/common/Comment.jsx

- 채팅 댓글 컴포넌츠 추가입니다
open : #
close : #

Feat: Comment 컴포넌트 추가(#12)

---

src/Components/common/Toggle.jsx

- Toggle 버튼 추가하였습니다!
open : #
close : #

Feat: 공통 컴포넌트 Toggle 추가 (#12)

---

src/Pages/Product/Product.jsx

- import 해온 Layout 구문 변경 (Layout -> {Layout})
open : #12 
close : #

Style: Layout import 구문 변경(#12)

---

package-lock.json
src/Components/HomePost/HomePostLayout.jsx
src/Components/common/CircleButton.jsx
src/Components/common/Navbar.jsx
src/Components/common/TopNavBar.jsx
src/GlobalStyle.jsx
src/Styles/Layout.jsx

- Navbar에 해당 경로로 이동시 icon color 변경
- Homepost 초기 디자인, 기능 생성
open : #12 
close : #

공통 컴포넌트 기능 추가

---

src/Components/Comment.jsx
src/Components/common/PostComment.jsx
src/Components/common/UploadedPost.jsx

- 게시물까지 합쳐서 페이지 완성 예정입니다
open : #36
close : #

Design: 게시물 상세 페이지 UI(#36)

---

src/App.js
src/Pages/Login.jsx
src/Pages/NotFound.jsx
src/test/images.js

- image테스트를 위한 test 폴더추가, Login 예외처리 기능 추가, 404페이지 Route추가
- 404페이지 디자인 추가
open : #17 #46  
close : #

404페이지, 로그인 페이지, Hompost 컴포넌트

---

src/Components/HomePost/HomePostLayout.jsx
src/Components/UploadedPost.jsx
src/Components/common/User.jsx

HomePostLayout에서 User컴포넌트 우측 moreBtn 추가
-
open : #
close : #36

Feat: HomePostLayout에서 User컴포넌트 우측 moreBtn 추가, 게시물 업로드 UI 완성

---

src/Pages/Product/AddProduct.jsx
src/Pages/Product/Product.jsx

Fix: import한 Header 경로 변경 및 import useNavigate추가

---

src/Pages/Home.jsx

- 마크업 ,스타일링
- 무한 스크롤
open : # 16
close : #

홈페이지 마크업, 무한스크롤 구현

---

src/App.js
src/Components/common/Navbar.jsx
src/Pages/Landing.jsx
src/Pages/Login.jsx
src/Utils/LoginAPI.jsx

- 홈의 루트였던 '/'이 '/home'으로 변경
- 랜딩 페이지가 '/'담당 
open : #70 
close : #

랜딩 페이지, App.js

---

src/Components/common/Navbar.jsx

- Navbar 레이아웃 및 보더 수정
open : #12
close : #

Fix: Navbar 레이아웃 및 보더 수정 (#12)

---

src/App.js
src/Components/common/Header/UploadHeader.jsx
src/Pages/Signup.jsx
src/Pages/UploadPost.jsx

Route(post) 경로 추가, 

---

src/Components/common/Navbar.jsx

-Navbar 내 백틱으로 인한 오류 수정
open : #12
close : #

Fix: Navbar 내 백틱으로 인한 오류 수정 (#12)

---

src/Components/Profile/UserProfile.jsx
src/Components/Profile/UserProfileSetting.jsx
src/Components/common/Input.jsx
src/Pages/Profile.jsx
src/Utils/UserInfoAPI.jsx

- input에 width 추가 (Default: 100%)
open : #12  #15 
close : #

프로필 페이지, 공통 컴포넌트 

---

package-lock.json
package.json
src/Components/common/Header/UploadHeader.jsx
src/Pages/Product/AddProduct.jsx

Feat: UploadHeader onClick props 추가(#12)

---

src/Pages/Home.jsx

- 홈포스트 태그 제거했습니다!
open : #16
close : #

Home 페이지 버그로 인해 HomePost 태그 제거

---

src/Components/HomePost/HomePostLayout.jsx
src/Components/common/Navbar.jsx
src/Components/common/User.jsx
src/Pages/Profile.jsx

- console.log 제거
open : #
close : #

Style: 불필요한 console.log 제거

---

src/Components/HomePost/HomePostLayout.jsx
src/Components/Profile/UserProfile.jsx

- HomePostLayout, UserProfile에 background-color 추가
open : #12 
close : #

Design: HomePostLayout, UserProfile에 background-color 추가 (#12)

---

src/Components/HomePost/HomePostLayout.jsx
src/Components/Profile/UserProfile.jsx
src/Pages/Profile.jsx

…변경, Profile 판매 중인 상품 디자인 추가 (#12, #15)
- HomePostLayout Layout 태그 변경
- UserProfile CommonButton 디자인 속성 변경
- Profile 판매 중인 상품 디자인 추가
open : #12 #15 
close : #

HomePostLayout, UserProfile,  Profile

---

src/Assets/icons/upload.svg
src/Components/common/CircleButton.jsx
src/Pages/Product/Product.jsx
src/Pages/UploadPost.jsx

CircleButton 기본 이미지 업로드 문제 해결, ImgUploadAPI 함수 분리

---

src/Components/common/Navbar.jsx
src/Pages/Product/AddProduct.jsx

Navbar active 아이콘 수정(#12)

---

src/Components/common/ProductItem.jsx
src/Pages/Profile.jsx
src/Pages/Signup.jsx
src/Utils/ProductListAPI.jsx

- ProductList API 추가
- ProductItem API 데이터 대응 props추가
- 프로필페이지에서 뿌려주기 
- 회원가입의 이미지 업로드 API를 공통 ImageUploadAPI로 변경
open : #15 
close : #

프로필 페이지, 공통 컴포넌트 ProductItem, 회원가입 페이지

---

src/Components/HomePost/HomePostLayout.jsx
src/Components/Profile/UserProfile.jsx
src/Components/common/User.jsx

-  Homepost moreBtn 변경 및 이미지 길이에 따른 화살표와 인디케이터 생성 여부
- UserProfile CommonButton navigate추가
- User 더보기 버튼 수정
open : #12  #15 
close : #

공통 컴포넌트, 프로필 페이지

---

src/Pages/Search.jsx

- 검색 페이지 검색시 디바운스 기능, 로딩시 스켈레톤UI 추가
open : #47
close : #

검색 페이지 검색시 디바운스 기능, 로딩시 스켈레톤UI 추가

---

src/App.js
src/Pages/Post.jsx
src/Utils/ImageUploadAPI.jsx
src/Utils/validate.js

Post 이미지의 close버튼 추가

---

src/Components/common/Skeleton/HomePostSkeleton.jsx
src/Components/common/Skeleton/UserSkeleton.jsx

- HomePostSkeleton내 UserSkeleton 컴포넌트화, 두 파일 다 common 폴더 내 Skeleton 폴더로 경로 변경하였습니다!
open : #12
close : #

HomePostSkeleton내 UserSkeleton 컴포넌트화, 경로 변경

---

src/Components/common/Skeleton/HomePostSkeleton.jsx
src/Components/common/Skeleton/UserSkeleton.jsx

- Skeleton폴더 내 파일들 오류로 인해 경로 변경했습니다!
open : #12
close : #

Skeleton폴더 내 파일 경로 변경

---

src/Pages/Home.jsx

- 홈페이지 피드 가져오는 API 추가
- 무한스크롤 적용
- 첫 로딩시 스켈레톤 UI 적용
open : #16
close : #

홈페이지 피드 가져오는 API 추가, 무한스크롤 적용, 첫 로딩시 스켈레톤 UI 적용

---

src/Components/common/AlertModal.jsx
src/Components/common/Header/BasicHeader.jsx
src/Components/common/Modal.jsx

- Basic Header의 더보기 버튼에 bottom modal 추가
- bottom modal에 AlertModal에 로그아웃 기능추가
open : #12 
close : #

공통 컴포넌트 Basic Header

---

src/App.js
src/Components/common/Navbar.jsx
src/Components/common/ProductItem.jsx
src/Pages/Product/AddProduct.jsx
src/Pages/Product/Product.jsx
src/Pages/Product/ProductDetail.jsx
src/Utils/ProductDetailAPI.jsx

- App.js 페이지 이동 경로 추가
- Product 페이지 상품 상세 페이지 구현
open : #14 
close : #

App.js 경로 변경 및 Product 페이지 기능 추가(#14)

---

src/Components/common/Header/BasicHeader.jsx

Feat: BasicHeader 모달창에 props 지정(#12)

---

src/Pages/Home.jsx

홈페이지 내 디폴트페이지 추가, 로딩 기능 리팩토링

---

src/Components/common/Header/BasicHeader.jsx
src/Pages/Product/ProductDetail.jsx
src/Utils/ProductDeleteAPI.jsx

HOTFIX: 상품 삭제 기능 오류 발생

---

src/Components/common/Header/BasicHeader.jsx
src/Utils/ProductDeleteAPI.jsx

- Product Detail의 Basic Header에서 삭제 눌렀을 경우 상품 삭제
- ProductDeleteAPI 파라미터 수정
open : #14 
close : #

Product Detail 페이지

---

src/Components/Profile/UserProfileSetting.jsx

- 사용하지 않는 파일 import 삭제
open : #
close : #

Style: 불필요한 import 제거

---

src/Components/common/ProductItem.jsx
src/Pages/Product/AddProduct.jsx
src/Pages/Product/Product.jsx
src/Pages/Product/ProductDetail.jsx
src/Pages/Product/ProductModification.jsx
src/Utils/ProductDeleteAPI.jsx
src/Utils/ProductDetailAPI.jsx
src/Utils/ProductListAPI.jsx

```
width: calc(100% + 16px + 12px); // Image 너비에 패딩값 차감
height: 232px;
margin-left: -16px;
margin-right: -12px;
```
- Addproduct에 판매 링크 대신 textarea로 상세설명 칸으로 교체 완료. 디자인 검토 요청.
open : #14 
close : #

Product 기능 구현(#14)

---

src/Pages/Product/AddProduct.jsx
src/Pages/Product/ProductDetail.jsx

AddProduct 상세 설명란 추가 및 스타일 지정(#14)

---

src/Components/Profile/UserProfile.jsx
src/Components/Profile/UserProfileSetting.jsx
src/Pages/Profile.jsx
src/Utils/AccountValidAPI.jsx
src/Utils/EditProfileAPI.jsx
src/Utils/UserInfoAPI.jsx

- 프로필 수정 계정ID 예외처리 추가
- AccountValidAPI추가
- 사용하지 않는 console.log 삭제
open : #15 
close : #

프로필 수정페이지 

---

src/Pages/Search.jsx

- 검색페이지 결과 모두 보기 버튼 추가 
open : #47
close : #

검색페이지 결과 모두 보기 버튼 추가 

---

src/Hooks/useFetch.jsx
src/Hooks/useInput.jsx
src/Pages/Product/Product.jsx

- 팔로잉 하는 유저의 판매상품으로 변경
- 커스텀 훅 (useFetch, useInput) 추가
open : #14 
close : #

상품 페이지, Hook

---

src/Components/common/Header/BasicHeader.jsx
src/Pages/Product/Product.jsx

- Product 페이지 더보기 버튼 클릭 시 설정 및 로그아웃 기능 추가
- BasicHeader 설정 및 개인정보 버튼 클릭 시 'userId'가 있는 경우에만 상품 수정이로 이동
-
open : #12, #14 
close : #

Product, BasicHeader 기능 구현(#12, #14)

---

src/App.js
src/Components/Profile/UserProfile.jsx
src/Components/common/FollowUser.jsx
src/Components/common/User.jsx
src/Pages/Followers.jsx
src/Pages/Profile.jsx
src/Utils/FollowAPI.jsx
src/Utils/FollowerListAPI.jsx
src/Utils/FollowingListAPI.jsx
src/Utils/MyInfoAPI.jsx
src/Utils/UnFollowAPI.jsx

- User 공통 컴포넌트 이미지 예외처리 
- FollowUser 공통 컴포넌트 생성, User와 분리 (다른 데이터 값으로 복잡도 상승으로 인해)
- Follow, Unfollow 기능 추가 및 API 추가
- Followers, Followings 페이지 추가 및 API 추가
- Follower, Following Route 추가 
open : #12  #15 
close : #

프로필 페이지, 공통 컴포넌트

---

src/Components/common/Skeleton/ProductItemSkeleton.jsx
src/Pages/Home.jsx
src/Pages/Product/Product.jsx

- 상품페이지 무한스크롤 구현
- 상품 아이템 중앙정렬
- 스켈레톤 UI 추가
- 리팩토링
open : #15 #16
close : #

상품페이지 무한스크롤 구현 및 리팩토링, 홈페이지 내 중복 요소 제거

---

src/Components/LoginMethod.jsx
src/Pages/Landing.jsx

- 랜딩페이지입니다!
open : #12
close : #

공통 컴포넌트 랜딩페이지 링크 기능 구현, 디자인

---

src/App.js
src/Components/Comment.jsx
src/Components/CommentModal.jsx
src/Components/HomePost/HomePostLayout.jsx
src/Components/HomePost/ViewImage.jsx
src/Components/PostModal.jsx
src/Components/common/Modal.jsx
src/Components/common/PostComment.jsx
src/Components/common/ProductItem.jsx
src/Hooks/useFetch.jsx
src/Pages/Login.jsx
src/Pages/PostDetail.jsx
src/Pages/PostModification.jsx
src/Utils/GetCommentAPI.jsx
src/Utils/PostCommentAPI.jsx
src/Utils/PostDetailAPI.jsx
src/Utils/ReportCommentAPI.jsx
src/Utils/UnFollowAPI.jsx

- 아직도 모달 배경 비칩니다 수정 예정!!
open : #102
close : #

수정 기능 이미지 로드 문제 수정, 구현 완료

---

src/Components/common/CircleButton.jsx
src/Pages/Product/AddProduct.jsx
src/Pages/Product/Product.jsx
src/Pages/Product/ProductDetail.jsx

- 상품 추가 페이지 : 글자 수, 가격 범위 제한 어길 시 에러메세지 표시
- 상품 상세 페이지 : line-height 추가
- CircleButton 감싸는 layout에 position: fixed 적용, CircleButton props margin 추가
-
open : #12, #14 
close : #

CircleButton, 상품 추가, 상품 상세 페이지 기능 및 디자인 추가(#12, #14)

---

src/Components/PostModal.jsx

Fix: PostModal props 전달 오류 수정

---

src/App.js
src/Components/common/AlertTop.jsx
src/Pages/Landing.jsx
src/Utils/ProtectRoute/ProtectRoute.jsx

- 경고 Top 모달 디자인 기존 AlertTop 컴포넌트에 props로 추가
- 랜딩페이지에서 미로그인시에 타경로로 접근 차단을 위한 ProtectRoute 생성 및 추가
- App.js에서 하위 요소 출력을 위한 Outlet 추가 
- Landing 컴포넌트에서 ProtectRoute 발생시 받아오는 location.state의 에러메세지 출력 
open : #70 
close : #

랜딩페이지, App.js

---

src/Components/common/User.jsx
src/Pages/Search.jsx

- 검색 페이지 내 검색 결과중 키워드와 일치하는 부분 프라이머리 색으로 하이라이팅되는 기능 추가
- User컴포넌트 내 chat 부분 삭제
open : #47
close : #

검색 페이지 검색 결과 하이라이팅 기능 및 유저 컴포넌트 리팩토링

---

src/Components/common/User.jsx

- User컴포넌트 내 오류나는 부분 옵셔널체이닝 추가
open : #12
close : #

User 컴포넌트 ProductDetail 페이지에서 오류나는 현상 수정

---

src/Components/Comment.jsx
src/Components/HomePost/HomePostLayout.jsx
src/Components/PostModal.jsx
src/Components/common/PostImage.jsx

- 급하게 커밋 올렸더니 오타가 많네요 죄삼다,,,^^
open : #102 
close : #

PostImage 컴포넌트 분리, 이미지 없을 경우 heart, comment를 게시글 하단에 오게 배치(#102)

---

src/Pages/Product/AddProduct.jsx
src/Pages/Product/ProductDetail.jsx
src/Utils/ProductListAPI.jsx
src/Utils/ProductModifyAPI.jsx

- 하단 가격 부분 줄간격 1.3, p 태그로 변경
- 채팅하기 버튼 margin-bottom 5px로 변경
-
open : #14 
close : #

ProductDetail css 수정(#14)

---

src/Pages/Product/ProductDetail.jsx

ProductDetail 줄바꿈 표시되게 수정(#14)

---

src/Components/Comment.jsx
src/Components/HomePost/HomePostLayout.jsx
src/Pages/PostDetail.jsx

- PostDetail에서 useParams로 값을 받아오는데 id로 받아와야 하는것을 까먹고 postId라고 통일을 주고 싶어서 멋대로 바꿨다가 이 사단이 났었습니다..  다들 주무실때라 문제가 없었길 희망하며,,,, 
open : #
close : #

🚑HOTFIX: 게시물 상세페이지 접근시 오류 해결입니다

---

src/Pages/Chat/Chat.jsx
src/Pages/Chat/ChatDetail.jsx
src/Pages/Product/Product.jsx

Feat: 더보기 버튼 클릭 시 모달 창에 설정, 로그아웃 나오게 설정(#14, #56)

---

src/Components/Comment.jsx
src/Components/CommentModal.jsx
src/Components/HomePost/HomePostLayout.jsx
src/Components/PostModal.jsx
src/Components/common/AlertModal.jsx
src/Components/common/Header/BasicHeader.jsx
src/Components/common/Modal.jsx
src/Components/common/PostAlertModal.jsx
src/Pages/PostModification.jsx

모달 뒷배경 추가로 다른 동작 방지, 게시글 수정시 이미지 불러오는 문제 해결

---

src/Components/Comment.jsx
src/Components/HomePost/HomePostLayout.jsx
src/Components/common/AlertTop.jsx

게시글/댓글 신고시 TopModal 추가(#139)

---

src/Components/common/Header/BasicHeader.jsx
src/Pages/Product/AddProduct.jsx
src/Pages/Product/Product.jsx
src/Pages/Product/ProductModification.jsx
src/Pages/Profile.jsx

- 상품 삭제 시, product 페이지로 이동 후 '삭제되었습니다.' 모달 표시
- 상품 수정 시, profile 페이지로 이동 후 '수정되었습니다.' 모달 표시
-
open : #14 
close : #

Product 수정, 삭제 시 완료 모달 표시(#14)

---

src/Components/common/AlertTop.jsx

AlertTop 수정(#12)

---

src/Components/common/Header/BasicHeader.jsx
src/Pages/Product/AddProduct.jsx
src/Pages/Product/Product.jsx
src/Pages/Profile.jsx

- 상품 추가/삭제 시, profile 페이지로 이동되게 변경
- 상품 페이지에서 더보기 버튼 삭제
-
open : #14 
close : #

상품 삭제, 상품 추가 시 이동 페이지 변경(#14)

---

src/Components/Comment.jsx
src/Components/common/PostComment.jsx
src/Pages/Post.jsx
src/Pages/PostDetail.jsx
src/Utils/GetNumerousCommentAPI.jsx

-사실 댓글 100개까지 한번에 받아온 후 더보기 버튼 클릭시 나타나게 했습니다,,^^
open : #
close : #102

게시글 댓글 여러개일 경우 최신순 5개씩 표시(#102)

---

src/Pages/Product/Product.jsx
src/Pages/Product/ProductDetail.jsx

Feat: 상품 디테일 페이지에서 더보기 버튼 삭제(#14)

---

src/Components/common/Header/BasicHeader.jsx

- BasicHeader 내 요소 수직 중앙정렬
open : #12
close : #

공통 컴포넌트 BasicHeader 내 요소 수직 중앙정렬

---

src/Pages/Home.jsx

- 커밋 컨벤션을 지키지 못했습니다.. 못난 저를 용서하지 마세요.. 정말 죄송합니다..
open : #16
close : #

홈페이지 스피너 끝나면 위로 조금 이동할 때 이동 방식 리팩토링

---

src/Components/Comment.jsx
src/Components/common/PostComment.jsx
src/Pages/PostDetail.jsx

댓글달기창 프로필 사진 로그인된 계정 프로필 사진으로 교체, 댓글창 레이아웃 조절

---

src/Pages/Chat/Chat.jsx
src/Pages/Product/Product.jsx
src/Pages/Product/ProductDetail.jsx

ProductDetail 수정/삭제 권한 변경(#14)

---

src/Components/HomePost/HomePostLayout.jsx
src/Components/common/Toggle.jsx
src/Pages/Homebackup.jsx
src/Pages/Post.jsx
src/Pages/PostModification.jsx

Co-authored-by: ystone0213@naver.com
-
open : #169
close : #

카테고리 기능 추가(#169)!!!!!!!!!

---

src/Pages/PostModification.jsx

Fix: 카테고리 기능 활성화 후  게시물 이미지 수정 문제(#169)

---

src/Pages/Followers.jsx

- Followers 페이지 헤더부분 렌더링 시 초기에 기존 단어로 나오는 버그 수정
open : #123
close : #

Followers 페이지 헤더부분 버그 수정

---

src/Components/common/AlertModal.jsx
src/Pages/Chat/ChatDetail.jsx
src/Pages/Product/ProductDetail.jsx
src/Utils/ProductDetailAPI.jsx

ChatDetail에서 내 프로필 이미지 보이게 기능 추가

---

src/Components/CommentModal.jsx
src/Components/HomePost/HomePostLayout.jsx
src/Components/HomePost/ViewImage.jsx
src/Components/PostModal.jsx
src/Components/common/Modal.jsx

모달 bottom여백, 게시물 cursor, 동작 제어

---

src/Pages/Search.jsx

- 검색 페이지 setTimeout 제거
open : #47
close : #

검색 페이지 setTimeout 제거

---

src/Components/HomePost/HomePostLayout.jsx
src/Components/common/PostComment.jsx
src/Pages/Post/PostDetail.jsx

Fix: comment 업데이트시 숫자 바로 반영 안되던 문제 해결(#102)

---

src/Components/Comment/CommentModal.jsx
src/Components/PostModal.jsx
src/Components/common/Modal/AlertTop.jsx
src/Components/common/Modal/Modal.jsx

모달 애니메이션 추가, AlertTop 모달 중첩 문제 해결

---

src/Components/common/Skeleton/ProductItemSkeleton.jsx
src/Components/common/User.jsx
src/Pages/Home.jsx

- 검색 페이지 계정 검색 시 이름이 긴 계정이 레이아웃을 뚫고 나가는 현상 수정
open : #47
close : #

검색 페이지 계정 검색 시 레이아웃을 뚫고 나가는 현상 수정

---

src/Components/Comment/CommentModal.jsx
src/Components/HomePost/HomePostLayout.jsx
src/Components/common/Modal/Modal.jsx
src/Pages/Product/AddProduct.jsx

AddProduct 10MB 넘는 이미지 예외처리, 다른 계정 접근시 오류 해결, 헤더모달 하단 여백 변경

---

src/Components/common/User.jsx

- 검색 페이지 이미지 예외처리 위해 User컴포넌트 수정
open : #193
close : #

검색 페이지 이미지 예외처리 위해 User컴포넌트 수정

---

src/Components/LoginMethod.jsx
src/GlobalStyle.jsx
src/Pages/Home.jsx
src/Pages/Post/PostDetail.jsx
src/Pages/Product/Product.jsx
src/Pages/Profile/Profile.jsx
src/Styles/Layout.jsx

- 최상단 min-height => heigt 변경으로 모바일 웹 대응 했지만 border 사라짐 현상이 나타나 Layout 내부 overflow시 scroll 생성으로 고침
open : #195 
close : #

 최상단 height 변경으로 border가 더 나타나지않는 현상 Layout 내부 Scroll 생성으로 수정(#195)

---

src/Components/common/Navbar.jsx
src/Pages/Product/ProductDetail.jsx
src/Pages/Profile/Profile.jsx

- 사용하지 않는 스타일 컴포넌트 태그 삭제
- 상품디테일 최상단 Layout 스타일 변경, 컬러값 변수로 변경
open : #
close : #

HOTFIX: 사용하지 않는 스타일 컴포넌트 태그 삭제

---

package-lock.json
package.json
src/Pages/Post/Post.jsx
src/Pages/Post/PostModification.jsx
src/Utils/validate.js

-압축 기능을 넣었으나 일부 파일(가로로 긴 파일로 예상) 추가시 이미지가 너무 많이 깨지는 문제가 있습니다… 다른 팀과 압축 옵션이 같음에도 불구하고 이런 에러가 뜨는데 어디를 더 수정해야 할지는 일단 추후 보완 예정..
참고 자료는 노션에 업데이트 해놨습니다
압축 전
압축 후
open : #192 
close : #

Post 이미지 압축 기능 추가

---

src/Components/HomePost/ViewImage.jsx

- 프로필 앨범보기 사진 배열 첫번째 사진으로 바꾸기
open : #202 
close : #

프로필 앨범보기 사진 배열 첫번째 사진으로 바꾸기

---

src/Components/common/PostImage.jsx

- 혹시 감도 별로면 말해주세요~~ distance 크기에 따라 조절하면 됩니다!
open : #206
close : #

모바일에서 HomePost 이미지 제스쳐로 넘기기

---

src/Components/common/PostImage.jsx

- 이미지 첫번째 슬라이드에는 왼쪽버튼, 마지막 슬라이드에는 오른쪽 버튼 안보이게 했습니다
open : #209 
close : #

Design: 이미지 슬라이드 첫번째와, 마지막 이미지에는 없애기

---

src/Components/HomePost/HomePostLayout.jsx
src/Components/common/Modal/ImageModal.jsx
src/Components/common/PostImage.jsx

-reactPortal을 사용했으나 이번 기능에서는 큰 효과는 없었습니다...
open : #210
close : #

이미지 클릭시 모달창으로 원본 띄우기

---

src/Pages/Product/AddProduct.jsx
src/Pages/Product/ProductModification.jsx

상품 등록페이지에서 이미지 미등록시 저장 버튼 비활성화, Layout border 수정

---

src/Components/LoginMethod.jsx
src/Pages/Chat/Chat.jsx
src/Pages/Chat/ChatDetail.jsx
src/Pages/Chat/ChatUser.jsx
src/Pages/Login.jsx
src/Pages/Signup.jsx

- 
open : #216 #209 
close : #

로그인 input focus, 랜딩페이지 스타일드 컴포넌트 에러, 채팅 상세 페이지

---

src/Pages/Product/ProductDetail.jsx

Feat: Product Detail에서 사진 클릭 시 원본 사진 모달로 띄우기

---

src/Components/PCNav/useIsDesktop.jsx
src/Pages/Chat/Chat.jsx
src/Pages/Home.jsx
src/Pages/Post/Post.jsx
src/Pages/Product/Product.jsx
src/Pages/Profile/Profile.jsx

- 각 페이지에 pc navbar 추가했습니다.
open : #
close : #

Refactor: PC NavBar 모듈화

---

src/Components/common/Navbar.jsx
src/Pages/Home.jsx
src/Pages/Product/Product.jsx
src/Pages/Profile/Profile.jsx
src/Styles/HeaderLayout.jsx
src/Styles/Layout.jsx

- Layout, Header, Bottom Nav 양쪽 border 삭제
- scroll을 해당 Layout기준에서 window 기준으로 변경
- Navbar 태그 footer로 변경
open : # 
close : #238

Border 삭제, Scroll 윈도우 기준 

---

package-lock.json
package.json
src/App.js
src/Components/common/Header/BasicHeader.jsx
src/Pages/Home.jsx

Feature: BasicHeader 내 로그아웃 버튼에 캐시 삭제 기능 추가

---

package-lock.json
package.json
src/App.js
src/Components/common/Header/BasicHeader.jsx
src/Pages/Home.jsx

Refactor: 홈페이지 카테고리 토글 버튼 상태저장

---

src/App.js
src/Components/PCNav/PCNavBar.jsx
src/Components/PCNav/useIsDesktop.jsx
src/Components/common/PostComment.jsx
src/Components/common/Topbutton.jsx
src/Pages/Chat/Chat.jsx
src/Pages/Chat/ChatDetail.jsx
src/Pages/Home.jsx
src/Pages/Post/Post.jsx
src/Pages/Post/PostDetail.jsx
src/Pages/Post/PostModification.jsx
src/Pages/Product/AddProduct.jsx
src/Pages/Product/Product.jsx
src/Pages/Product/ProductDetail.jsx
src/Pages/Product/ProductModification.jsx
src/Pages/Profile/Followers.jsx
src/Pages/Profile/Profile.jsx
src/Pages/Search.jsx
src/Recoil/isDesktop/isDesktop.js
src/Styles/Layout.jsx
src/index.js

- PC버전의 경우 Layout width 480px으로 변경
open : #
close : #

PC버전 Layout Width 변경, isDesktop Recoil관리, PCNavbar 수정

---

src/Pages/Home.jsx

- 홈페이지 내 새글 불러오기 오류나는 현상 수정 및 누락된 수정사항 보완
open : #243
close : #

홈페이지 내 새글 불러오기 오류나는 현상 수정 및 누락된 수정사항 보완

---

src/Components/Home/MyPillowers.jsx
src/Components/common/FollowUser.jsx
src/Pages/Home.jsx

- My pillowers 컴포넌트 생성, 홈페이지에 추가
- PC 사이즈인지에 따라서 My pillowers 온오프
- isPCScreen에 따라 랜더링 할경우 데이터 값을 매번 불러와서 느리게 나오는 현상 발생으로 display를 사용함
open : #
close : #246

My pillowers 컴포넌트 생성

---

src/Components/common/ProductItem.jsx
src/Pages/Product/Product.jsx
src/Recoil/productCategory/productCategory.js

Feat: 상품/외화 카테고리 저장

---

src/Pages/Chat/Chat.jsx
src/Pages/Chat/ChatDetail.jsx
src/Pages/Chat/ChatUser.jsx
src/Pages/Home.jsx
src/Pages/Post/Post.jsx
src/Pages/Post/PostDetail.jsx
src/Pages/Post/PostModification.jsx
src/Pages/Product/AddProduct.jsx
src/Pages/Product/Product.jsx
src/Pages/Product/ProductDetail.jsx
src/Pages/Product/ProductModification.jsx
src/Pages/Profile/Followers.jsx
src/Pages/Profile/Profile.jsx
src/Pages/Profile/Setting.jsx
src/Pages/Profile/UserProfileSetting.jsx

- 각 페이지 PC버전시 헤더삭제 
-  프로필 수정, 게시물 수정, 게시물 업로드, 상품 업로드 PC버전 버튼 위치 변경 
- 상품상세 PC버전 가격, 채팅하기 버튼 위치 변경
- 채팅
- PC버전시에 chatDetail로 이동안함 
- PC버전시에 chat에 chatDetail 바로 띄워주기
- location으로 값을 받아오기에 isPCScreen 감지해서 state 값 계속 보내주기
- 많은 렌더링이 일어나는 문제는 있을 수 있음, 점검 필요
open : #252
close : #

PC버전 헤더 대응, 채팅 PC, 업로드 PC

---

src/App.js
src/Components/Home/MyPillowings.jsx
src/Pages/Home.jsx
src/Pages/Post/Post.jsx
src/Pages/Post/PostDetail.jsx
src/Pages/Post/PostModification.jsx
src/Pages/Product/AddProduct.jsx
src/Pages/Product/Product.jsx
src/Pages/Product/ProductDetail.jsx
src/Pages/Product/ProductModification.jsx
src/Pages/Profile/Followers.jsx
src/Pages/Profile/Profile.jsx
src/Pages/Profile/UserProfileSetting.jsx

- App.js에서 useLocation사용으로 인한 업데이트로 react-query refetch 에러 수정 
- MyPillowings가 필요한 페이지 컴포넌트에 추가
- 상품디테일 PC버전일때 TopNav 안보이게 수정 
open : #269 
close : #

useLocation사용으로 인한 useQuery refetch 현상 수정

---

src/Components/PCNav/PCNavBar.jsx
src/Components/common/Header/SearchHeader.jsx
src/Components/common/Modal/PCNavbarModal.jsx
src/Components/common/User.jsx
src/Pages/Search.jsx

- PC버전 검색창 추가
- 검색창 내에서 유저 이미지 클릭시에만 프로필로 넘어갔던 것을 해당 유저 범위 전체로 변경
open : #263
close : #

Feat: PC버전 검색창 추가 및 검색창 내 유저 클릭 범위 변경(#263)

---

src/App.js
src/Router/AppRoutes.jsx

- 기존 랜딩,로그인,회원가입을 ProtectRoute로 분리되어있는 Router에 추가 
- 현재 App.js에서 useLocation 등과 같은 업데이트 훅 사용시 refetch되는 현상으로 path로 조건부 렌더링 불가
open : #
close : #274

PCNav 랜딩,로그인,회원가입 페이지에서 제외

---

src/Components/common/User.jsx

Bug: User 내 더보기 버튼 누를 시 프로필로 이동되는 버그 수정 (#281)

---

src/Pages/Product/ProductDetail.jsx

- 상품상세 채팅하기 버튼 위치 수정
open : #
close : #264

상품상세에서 채팅하기 버튼 위치 수정

---

src/Pages/Post/PostDetail.jsx

댓글 시간순 구현, 더보기 하단 배치

---

package-lock.json
package.json
src/Components/common/Modal/PostAlertModal.jsx
src/Pages/Post/Post.jsx
src/Pages/Post/PostModification.jsx
src/Pages/Profile/Profile.jsx

- 노션에 링크 올려두었습니다 상품 적용시 참고하시면 될것같아요~~
open : #286 
close : #

게시글 업로드, 수정 throttle적용

---

src/App.js
src/Components/TabNav/TabNavBar.jsx
src/Components/TabNav/useIsTablet.jsx
src/Pages/Chat/Chat.jsx
src/Pages/Product/AddProduct.jsx
src/Pages/Product/Product.jsx
src/Pages/Product/ProductModification.jsx
src/Recoil/isTab/isTab.js

상품 업로드, 수정 throttle적용

---

src/Components/TabNav/useIsTablet.jsx
src/Components/common/Modal/PCModal.jsx
src/Pages/Product/AddProduct.jsx
src/Pages/Product/ProductDetail.jsx
src/Pages/Product/ProductModification.jsx

Fix: 상품 디테일 더보기 버튼 클릭 시 fillowings도 같이 보이는 현상 수정

---

src/Components/Sign/SignupForm.jsx
src/Hooks/Sign/useSignup.jsx
src/Pages/Profile/UserProfileSetting.jsx
src/Utils/uploadFile.js

- 이미지 업로드 함수 handleImageInput => uploadFile로 네이밍 변경 후 재사용 함수로 분리
- 프로필 수정 및 회원가입 시에 재사용
open : #299 
close : #

이미지 업로드 에러 수정

---

src/App.js
src/Components/common/Modal/PCAlertModal.jsx

- useIsDesktop App.js에 추가
- 로그아웃시 이동 페이지 수정
open : #
close : #

useIsDesktop 추가, 로그아웃시 이동 페이지 수정

---

src/Api/Product/ProductDetailAPI.jsx
src/Api/Profile/FollowerListAPI.jsx
src/Api/Profile/FollowingListAPI.jsx
src/Api/Profile/MyInfoAPI.jsx
src/App.js
src/Components/Home/MyPillowings.jsx
src/Components/Profile/ProfileMain.jsx
src/Components/Sign/LoginForm.jsx
src/Components/common/FollowUser.jsx
src/Components/common/Modal/PCAlertModal.jsx
src/Hooks/useFollowing.jsx
src/Pages/Login.jsx
src/Pages/Profile/Followers.jsx
src/Pages/Profile/Profile.jsx
src/Pages/Profile/UserProfileSetting.jsx

- useEffect 의존성 배열 수정 
- Follow User 중복적으로 사용되어 필요없는 기능 삭제 
- useEffect에서 함수 의존성 배열에 추가시, 무한렌더링 방지를 위해 useCallback으로 메모이제이션 
- 바로 전 PR 커밋도 함께 있는데 까먹을거같아서 올려요!! 
open : #304 
close : #

useEffect 내 사용 함수 메모이제이션, ESLint 에러

---

src/Pages/Home.jsx

Bug: 홈페이지 스크롤 최하단 도달 후 새 페이지 불러올때 오류,  팔로우 목록 없을 때 Empty페이지 안 뜨는 버그 수정 (#307)

---

src/Components/PCNav/PCNavBar.jsx
src/Components/TabNav/TabNavBar.jsx
src/Components/common/Button.jsx
src/Components/common/CircleButton.jsx
src/Components/common/Header/BasicHeader.jsx
src/Components/common/Header/UploadHeader.jsx
src/Components/common/Navbar.jsx
src/Components/common/ProductItem.jsx
src/Components/common/Toggle.jsx
src/Pages/Product/AddProduct.jsx
src/Pages/Product/ProductDetail.jsx
src/Pages/Product/ProductModification.jsx

컴포넌트에 버튼 aria-label, 이미지 alt 추가

---

src/Pages/Product/ProductDetail.jsx

Fix: 상품 삭제 버튼 클릭 시, 모달 배경이 겹치는 현상 수정

---

src/Pages/Product/AddProduct.jsx
src/Pages/Product/ProductModification.jsx
src/Styles/ProductSharedStyles.jsx

Refactor: 상품 추가/수정에서 사용하는 공통된 스타일 분리

---

src/Components/common/ProductItem.jsx
src/Components/common/Skeleton/ProductItemSkeleton.jsx
src/Pages/Product/Product.jsx

Design: isWideView 일때, product & product skeleton image 크기 확대

---

src/Components/Chat/ChatContent.jsx
src/Components/SideNav/SideNavBar.jsx
src/Components/Sign/LoginForm.jsx
src/Components/Sign/SignupForm.jsx
src/Pages/Profile/UserProfileSetting.jsx

- 프로필, 로그인, 회원가입 input aria label 추가
- side nav shadow 색상 변경, blur 정도 변경
open : #304 
close : #

Input aria label, Side Nav

---

src/Pages/Product/LazyLoadedProductItem.jsx
src/Pages/Product/Product.jsx

- 처음에 상품 탭 들어가면 보이는 스켈레톤 제거하고, 대신에 사진이 로딩되기 전까지 스켈레톤 보이게 수정.
- 현재는 이미지 재업로드를 안해서 사진 뜨는 속도가 다 다른데, 사진 재업로드 후에도 스켈레톤 뜨는 속도가 다르면 예전처럼 수정 예정.
open : #328 
close : #

Refactor: 이미지 레이지로딩 적용 

---

src/Pages/Product/LazyLoadedProductItem.jsx
src/Pages/Product/Product.jsx

Product useQuery 코드 간소화

---

src/App.js
src/Components/Comment/Comment.jsx
src/Components/SideNav/useCheckDevice.jsx
src/Utils/timeGapCalculator.js

댓글 작성 시간별 표기법 교체

---

src/Components/common/Toggle.jsx
src/Pages/Product/ProductModification.jsx

Fix: 상품 카테고리 외화로 설정 안되는 오류 수정

---

src/Components/Search/SearchContent.jsx
src/Components/Search/SearchModal.jsx
src/Components/SideNav/SideNavBar.jsx
src/Components/common/Header/SearchHeader.jsx
src/Components/common/User.jsx

Search 페이지

---

src/Pages/Product/AddProduct.jsx
src/Pages/Product/Product.jsx
src/Pages/Product/ProductModification.jsx

Fix: 상품 수정 시 카테고리가 용품으로 자동으로 바뀌는 현상 수정

---

src/Components/Profile/UserProfile.jsx
src/Components/common/Skeleton/PCProfileSkeleton.jsx
src/Components/common/Skeleton/ProfileSkeleton.jsx

PC 버전 프로필 유저 스켈레톤 

---

src/Api/Post/GetPostAPI.jsx
src/Components/Profile/ProfileMain.jsx
src/Hooks/usePostInfinity.jsx

- GetPostAPI `limit=Number` 전체 불러오기로 변경
- 프로필 포스트 무한 스크롤 구현 
- 🤔 궁금한점
- 윤석이와 거의 똑같이 했는데 usePostInfinity 파일 68번줄 의존성 배열에 setPostList를 넣어줘야한다고 경고가 뜨는데 Home파일에서는 그렇지 않음. 이유를 못찾은 상태.. 
- useCallback으로 `setPostList` 함수를 감싸서 의존성배열에 postCount를 주었지만 계속 메모이제이션 된 결과값이 무한스크롤 되어서 실패 
- 다른 관련 변수도 의존성에 넣어주었지만 실패 
- 그래서 결국 uesCallback을 포기하고 eslint-disable-next-line을 넣어준 상태. 이부분은 공부가 필요합니다🥲
open : #
close : #304

프로필 포스트 무한스크롤

---

src/Pages/Product/Product.jsx
src/Recoil/navbarIcon/navbarIcon.js

상품 staleTime 추가

---

src/App.js
src/Components/HomePost/HomePostLayout.jsx
src/Components/Profile/ProfileMain.jsx
src/Hooks/usePostInfinity.jsx
src/Pages/Post/Post.jsx
src/Pages/Post/PostModification.jsx

- React Query Dev tool 설치 (npm i 필요!!)
- `removePostCacheData` 함수로 기존의 캐시데이터를 삭제 하여 다시 불러오는 방식 
```jsx
const removePostCacheData = () => {
queryClient.removeQueries('postList');
};
```
- `handleNewPostUpload` 함수 (쿼리 무효화)는 캐시 데이터에 영향이 주어지지않음 추가로 더 알아봐야할 것 같음 
- 현재 삭제시에는 `removePostCacheData()`함수 및 `handleNewPostUpload()` 함수를 사용하여도 데이터에 이상만 생길 뿐 제대로 동작하지 않음. 같은 엔드포인트 내에서 하는 거다 보니 임의로 새로고침 기능을 넣었음. (🐞재수정 필요)
> 업로드, 수정은 완료인듯!! 
open : #360 
close : #

프로필 게시물 업데이트 에러 수정 (업로드, 수정, 삭제)

---

src/Components/HomePost/HomePostLayout.jsx

같은 HomePostLayout 컴포넌트를 사용하면서 usePostInfinity에서 에러 발생
- 홈페이지, 프로필이 같은 HomePostLayout을 사용하기에 usePostInfinity의 함수를 사용하려다보니 undefined가 들어가는 에러 발생
- remove 함수를 HomePostLayout에 따로 선언하여 사용
open : #
close : #

HOTFIX: usePostInfinity undefined 에러 해결

---

src/Components/Profile/ProfileMain.jsx
src/Pages/Product/AddProduct.jsx

- 상품 등록, 삭제 시 업데이트 안되는 에러 해결
- `staleTime` 제거 
- 상품 등록시 이미지 선택 창에서 취소 버튼 누를 때 에러 해결 
```jsx
const handleImgChange = async (e) => {
const file = e.target?.files[0];
if (!file) { // 새로 추가한 조건문
return;
} else if (file.size > 10 * 1024 * 1024) {
alert('[ERROR 이미지 용량이 10MB를 넘습니다]');
return null;
} else if (!validateImageFileFormat(file.name)) return alert('파일 확장자를 확인해주세요');
await uploadFile(e, (imageUrl) => {
setImageLink(URL + '/' + imageUrl);
});
}
```
open : #
close : #

상품등록 삭제 업데이트 에러, 상품 이미지 선택창 취소시 에러

---

src/Utils/validate.js

Feat: 이미지 확장자 추가

---

.gitignore
src/App.js
src/Components/Home/MyPillowings.jsx

- ignore 추가
- React query Dev tool NODE_ENV가 development일 때만 렌더링
- following list length가 0보다 크면 렌더링
open : #
close : #

refactor: ignore 추가, Devtool 조건부 렌더링, following length로 연산

---

src/Api/Auth/CheckTokenAPI.jsx
src/App.js
src/Hooks/useCheckToken.jsx

- 일단 app.js의 checkDevice 아래에 위치시켰습니다
open : #
close : #

check valid token

---

src/Components/Profile/ProfileMain.jsx
src/GlobalStyle.jsx

- global font-famliy 추가 
- product textarea font-famliy 적용
- 프로필 게시물 렌더링 조건 추가
- 이전에 게시물 없음 표시가 먼저 나오고 렌더링 되었음
- 판매 상품을 최신순부터 렌더링  
open : #
close : #

font-famliy, 판매 상품 렌더링 순서, 게시물 렌더링 조건
